name: Maryland Photo Booths
favicon: null
layout_spectrum: 0.6860005990602076
typography_spectrum: 0.3132958591450006
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#ed1b24'
    - '#fdc81a'
    - '#000000'
    - '#f68086'
  brandStrength: 0.75
  lightness: 0.7662467786576599
  saturation: 0.4193071813788265
  rhythmicContrast: 0.5
purpose: []
